CREATE TABLE faculty (
  FACULTY_ID VARCHAR(50) PRIMARY KEY,
  FACULTY_NAME VARCHAR(50),
  OFFICE VARCHAR(50)
);


INSERT INTO FACULTY (FACULTY_ID, FACULTY_NAME, OFFICE)
VALUES 
  ('A52990', 'BLACK ANDERSON', 'MTC-218'),
  ('A77587', 'DEBBY ANGLES', 'MTC230'),
  ('B66750', 'ALICE BROWN', 'MTC-257');

CREATE TABLE COURSES (
  COURSE_ID VARCHAR(50) PRIMARY KEY,
  COURSE VARCHAR(50),
  FACULTY_ID VARCHAR(50),
  CONSTRAINT fk_faculty_id FOREIGN KEY (FACULTY_ID) REFERENCES faculty (FACULTY_ID)
);

INSERT INTO COURSES (COURSE_ID, COURSE, FACULTY_ID)
VALUES 
  ('CMP-6003', 'Introduction to Computer Science', 'A52990'),
  ('CMP-3023', 'Data Structures and Algorithms', 'A77587'),
  ('CSC-132A', 'Database Systems', 'A77587'),
  ('CMP-1001', 'Software Engineering', 'B66750');
